// Auto-generated TypeScript client for Ultimo RPC (JSON-RPC Mode)
// DO NOT EDIT - This file is automatically generated

export class UltimoRpcClient {
  constructor(private baseUrl: string = '/api/rpc') {}

  private async call<T>(method: string, params: any): Promise<T> {
    const response = await fetch(this.baseUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ method, params }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.message || 'RPC call failed');
    }

    const data = await response.json();
    return data.result;
  }

  async listUsers(params: {}): Promise<{ users: User[]; total: number }> {
    return this.call('listUsers', params);
  }

  async getUserById(params: { id: number }): Promise<User> {
    return this.call('getUserById', params);
  }

  async createUser(params: { name: string; email: string }): Promise<User> {
    return this.call('createUser', params);
  }

}

// Type Definitions
export interface User {
  id: number;
  name: string;
  email: string;
}
