// Auto-generated TanStack Query hooks for Ultimo RPC
// DO NOT EDIT - This file is automatically generated
import { createContext, createElement, useContext, type ReactNode } from 'react';
import {
  useQuery,
  useMutation,
  type UseQueryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';
import { UltimoRpcClient } from './client';

const ClientContext = createContext<UltimoRpcClient | null>(null);

export function UltimoProvider(props: { client: UltimoRpcClient; children: ReactNode }) {
  return createElement(ClientContext.Provider, { value: props.client }, props.children);
}

function useUltimoClient(): UltimoRpcClient {
  const client = useContext(ClientContext);
  if (!client) {
    throw new Error('useUltimoClient must be used within <UltimoProvider>');
  }
  return client;
}

export const queryKeys = {
  listUsers: (input: Parameters<UltimoRpcClient['listUsers']>[0]) => ['listUsers', input] as const,
  getUserById: (input: Parameters<UltimoRpcClient['getUserById']>[0]) => ['getUserById', input] as const,
};

export function useListUsers(
  input: Parameters<UltimoRpcClient['listUsers']>[0],
  options?: Omit<UseQueryOptions<Awaited<ReturnType<UltimoRpcClient['listUsers']>>>, 'queryKey' | 'queryFn'>,
) {
  const client = useUltimoClient();
  return useQuery({
    queryKey: queryKeys.listUsers(input),
    queryFn: () => client.listUsers(input),
    ...options,
  });
}

export function useGetUserById(
  input: Parameters<UltimoRpcClient['getUserById']>[0],
  options?: Omit<UseQueryOptions<Awaited<ReturnType<UltimoRpcClient['getUserById']>>>, 'queryKey' | 'queryFn'>,
) {
  const client = useUltimoClient();
  return useQuery({
    queryKey: queryKeys.getUserById(input),
    queryFn: () => client.getUserById(input),
    ...options,
  });
}

export function useCreateUser(
  options?: UseMutationOptions<Awaited<ReturnType<UltimoRpcClient['createUser']>>, Error, Parameters<UltimoRpcClient['createUser']>[0]>,
) {
  const client = useUltimoClient();
  return useMutation({
    mutationFn: (input: Parameters<UltimoRpcClient['createUser']>[0]) => client.createUser(input),
    ...options,
  });
}

