# Label PRs based on changed files

# Core framework
"area: core":
  - changed-files:
    - any-glob-to-any-file:
      - ultimo/src/**/*
      - ultimo/Cargo.toml

# RPC system
"area: rpc":
  - changed-files:
    - any-glob-to-any-file:
      - ultimo/src/rpc.rs
      - ultimo/src/rpc/**/*

# OpenAPI
"area: openapi":
  - changed-files:
    - any-glob-to-any-file:
      - ultimo/src/openapi.rs
      - ultimo/src/openapi/**/*

# Database
"area: database":
  - changed-files:
    - any-glob-to-any-file:
      - examples/database-**/*
      - ultimo/src/database.rs

# CLI
"area: cli":
  - changed-files:
    - any-glob-to-any-file:
      - ultimo-cli/**/*

# Examples
"area: examples":
  - changed-files:
    - any-glob-to-any-file:
      - examples/**/*

# Documentation
"area: docs":
  - changed-files:
    - any-glob-to-any-file:
      - docs/**/*
      - docs-site/**/*
      - "*.md"
      - website/**/*

# Tests
"type: test":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.test.rs"
      - "**/tests/**/*"
      - coverage-tool/**/*

# CI/CD
"type: chore":
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**/*
      - .github/**/*
      - scripts/**/*
      - Makefile
