// Auto-generated TypeScript client for Ultimo RPC (JSON-RPC 2.0)
// DO NOT EDIT - This file is automatically generated

export interface JsonRpcError {
  code: number;
  message: string;
  data?: unknown;
}

export class JsonRpcClientError extends Error {
  constructor(public readonly error: JsonRpcError) {
    super(error.message);
    this.name = "JsonRpcClientError";
  }
}

export interface User {
  id: number;
  name: string;
  email: string;
}

export interface UserListResponse {
  users: User[];
  total: number;
}

export class UltimoRpcClient {
  private _idCounter = 0;

  constructor(private baseUrl: string = "/api/rpc") {}

  private nextId(): number {
    return ++this._idCounter;
  }

  private async call<T>(method: string, params: unknown): Promise<T> {
    const id = this.nextId();
    const response = await fetch(this.baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", method, params, id }),
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    if (data.error) {
      throw new JsonRpcClientError(data.error);
    }
    return data.result as T;
  }

  /** Send a notification (fire-and-forget, no response expected) */
  async notify(method: string, params?: unknown): Promise<void> {
    await fetch(this.baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", method, params }),
    });
  }

  /** Execute multiple RPC calls in a single HTTP request */
  async batch<T extends Array<{ method: string; params?: unknown }>>(
    calls: T
  ): Promise<Array<{ result?: unknown; error?: JsonRpcError }>> {
    const requests = calls.map((call) => ({
      jsonrpc: "2.0" as const,
      method: call.method,
      params: call.params,
      id: this.nextId(),
    }));

    const response = await fetch(this.baseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requests),
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data: Array<{ result?: unknown; error?: JsonRpcError; id: number }> =
      await response.json();

    // Sort by id to match input order
    const sorted = requests.map((req) => {
      const res = data.find((r) => r.id === req.id);
      return res
        ? { result: res.result, error: res.error }
        : { error: { code: -1, message: "No response" } };
    });

    return sorted;
  }

  async listUsers(params: Record<string, unknown>): Promise<UserListResponse> {
    return this.call("listUsers", params);
  }

  async getUser(params: { id: number }): Promise<User> {
    return this.call("getUser", params);
  }

  async createUser(params: { name: string; email: string }): Promise<User> {
    return this.call("createUser", params);
  }
}
